[package]
name = "move-vm-config"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
move-binary-format.workspace = true
once_cell.workspace = true

[features]
tracing = []
